// Standalone mock data so the ProgramPage renders fully in MOCK_API mode
// (the default). Models a running program mid-flight: week 1 is the current,
// committed week with two finished trains and two still ahead; week 2 is a
// tentative preview the generator may still revise.

import type { Program, PlannedSession } from '../domain/types';

export const MOCK_PROGRAM: Program = {
  id: 'prog_mock_1',
  discipline: 'running',
  goalSnapshot: {
    primaryGoal: 'Run a sub-50:00 10K',
    note: 'First serious race in two years — build steadily, stay injury-free.',
    horizon: '2026-08-23',
  },
  startDate: '2026-06-15',
  horizonDate: '2026-08-23',
  status: 'active',
  currentWeekIndex: 1,
  weeks: [
    {
      weekIndex: 0,
      startDate: '2026-06-15',
      endDate: '2026-06-21',
      theme: 'base',
      plannedLoadTarget: 28,
      planState: 'committed',
      status: 'done',
      generatedAt: '2026-06-14T18:00:00.000Z',
    },
    {
      weekIndex: 1,
      startDate: '2026-06-22',
      endDate: '2026-06-28',
      theme: 'base',
      plannedLoadTarget: 32,
      planState: 'committed',
      status: 'current',
      generatedAt: '2026-06-21T18:00:00.000Z',
    },
    {
      weekIndex: 2,
      startDate: '2026-06-29',
      endDate: '2026-07-05',
      theme: 'build',
      plannedLoadTarget: 36,
      planState: 'tentative',
      status: 'upcoming',
      generatedAt: '2026-06-21T18:00:00.000Z',
    },
    {
      weekIndex: 3,
      startDate: '2026-07-06',
      endDate: '2026-07-12',
      theme: 'build',
      plannedLoadTarget: 40,
      planState: 'tentative',
      status: 'upcoming',
      generatedAt: null,
    },
  ],
};

// ── helpers ────────────────────────────────────────────────────────────────
const TZ = 'Europe/Berlin';

function run(
  partial: Partial<PlannedSession> & Pick<PlannedSession, 'id' | 'scheduledDate'>,
): PlannedSession {
  return {
    programId: 'prog_mock_1',
    weekIndex: 1,
    type: 'running',
    startTime: '07:00',
    endTime: '08:00',
    timezone: TZ,
    scheduledStartUtc: `${partial.scheduledDate}T05:00:00.000Z`,
    planState: 'committed',
    title: 'Run',
    estDurationMin: 60,
    intensityLabel: 'Easy',
    coachNotes: null,
    running: null,
    strength: null,
    outcome: {
      status: 'planned',
      reasonCode: null,
      perceivedEffort: null,
      enjoyment: null,
      matchedActivityId: null,
      feedbackRef: null,
      recordedAt: null,
    },
    ...partial,
  };
}

export const MOCK_PLANNED_SESSIONS: PlannedSession[] = [
  // ── Week 1 (current, committed) ──
  run({
    id: 'ps_1',
    scheduledDate: '2026-06-22',
    title: 'Easy aerobic run',
    intensityLabel: 'Easy',
    estDurationMin: 45,
    coachNotes: 'Conversational pace. Keep HR in zone 2 — this is recovery mileage.',
    running: {
      runType: 'easy',
      totalDistanceKm: 7,
      totalDurationMin: 45,
      targetPace: '6:25/km',
      targetHrZone: 2,
      targetRpe: 3,
      segments: [],
    },
    outcome: {
      status: 'completed',
      reasonCode: null,
      perceivedEffort: 3,
      enjoyment: 4,
      matchedActivityId: 88123,
      feedbackRef: null,
      recordedAt: '2026-06-22T06:10:00.000Z',
    },
  }),
  run({
    id: 'ps_2',
    scheduledDate: '2026-06-24',
    title: 'Interval session — 6×800m',
    intensityLabel: 'Hard',
    estDurationMin: 55,
    coachNotes: 'Hit 10K goal pace on the reps. Full recovery between.',
    running: {
      runType: 'intervals',
      totalDistanceKm: 9,
      totalDurationMin: 55,
      targetPace: null,
      targetHrZone: 4,
      targetRpe: 8,
      segments: [
        {
          kind: 'warmup',
          repeat: 1,
          distanceM: 2000,
          durationSec: null,
          targetPace: '6:30/km',
          targetHrZone: 2,
          restSec: null,
        },
        {
          kind: 'work',
          repeat: 6,
          distanceM: 800,
          durationSec: null,
          targetPace: '4:45/km',
          targetHrZone: 4,
          restSec: 120,
        },
        {
          kind: 'cooldown',
          repeat: 1,
          distanceM: 1500,
          durationSec: null,
          targetPace: '6:30/km',
          targetHrZone: 2,
          restSec: null,
        },
      ],
    },
    outcome: {
      status: 'partially_completed',
      reasonCode: 'too_hard',
      perceivedEffort: 9,
      enjoyment: 2,
      matchedActivityId: 88341,
      feedbackRef: null,
      recordedAt: '2026-06-24T06:05:00.000Z',
    },
  }),
  run({
    id: 'ps_3',
    scheduledDate: '2026-06-26',
    title: 'Tempo run',
    intensityLabel: 'Moderate',
    estDurationMin: 50,
    coachNotes: 'Comfortably hard middle block. Settle into a rhythm you could hold for an hour.',
    running: {
      runType: 'tempo',
      totalDistanceKm: 8,
      totalDurationMin: 50,
      targetPace: '5:20/km',
      targetHrZone: 3,
      targetRpe: 6,
      segments: [
        {
          kind: 'warmup',
          repeat: 1,
          distanceM: 1500,
          durationSec: null,
          targetPace: '6:30/km',
          targetHrZone: 2,
          restSec: null,
        },
        {
          kind: 'work',
          repeat: 1,
          distanceM: 5000,
          durationSec: null,
          targetPace: '5:20/km',
          targetHrZone: 3,
          restSec: null,
        },
        {
          kind: 'cooldown',
          repeat: 1,
          distanceM: 1500,
          durationSec: null,
          targetPace: '6:30/km',
          targetHrZone: 2,
          restSec: null,
        },
      ],
    },
  }),
  run({
    id: 'ps_4',
    scheduledDate: '2026-06-28',
    title: 'Long run',
    intensityLabel: 'Easy',
    estDurationMin: 80,
    startTime: '08:30',
    endTime: '09:50',
    scheduledStartUtc: '2026-06-28T06:30:00.000Z',
    coachNotes: 'Time on feet. Keep it easy the whole way — last 10 min can lift slightly.',
    running: {
      runType: 'long',
      totalDistanceKm: 14,
      totalDurationMin: 80,
      targetPace: '6:20/km',
      targetHrZone: 2,
      targetRpe: 4,
      segments: [],
    },
  }),

  // ── Week 2 (tentative preview) ──
  run({
    id: 'ps_5',
    weekIndex: 2,
    scheduledDate: '2026-06-29',
    planState: 'tentative',
    title: 'Easy aerobic run',
    intensityLabel: 'Easy',
    estDurationMin: 50,
    coachNotes: 'Recovery from the weekend long run.',
    running: {
      runType: 'easy',
      totalDistanceKm: 8,
      totalDurationMin: 50,
      targetPace: '6:20/km',
      targetHrZone: 2,
      targetRpe: 3,
      segments: [],
    },
  }),
  run({
    id: 'ps_6',
    weekIndex: 2,
    scheduledDate: '2026-07-01',
    planState: 'tentative',
    title: 'Hill repeats — 8×45s',
    intensityLabel: 'Hard',
    estDurationMin: 55,
    coachNotes: 'Strong but controlled uphill. Jog down to recover.',
    running: {
      runType: 'hills',
      totalDistanceKm: 9,
      totalDurationMin: 55,
      targetPace: null,
      targetHrZone: 4,
      targetRpe: 8,
      segments: [
        {
          kind: 'warmup',
          repeat: 1,
          distanceM: 2000,
          durationSec: null,
          targetPace: '6:30/km',
          targetHrZone: 2,
          restSec: null,
        },
        {
          kind: 'work',
          repeat: 8,
          distanceM: null,
          durationSec: 45,
          targetPace: null,
          targetHrZone: 4,
          restSec: 90,
        },
        {
          kind: 'cooldown',
          repeat: 1,
          distanceM: 1500,
          durationSec: null,
          targetPace: '6:30/km',
          targetHrZone: 2,
          restSec: null,
        },
      ],
    },
  }),
  run({
    id: 'ps_7',
    weekIndex: 2,
    scheduledDate: '2026-07-03',
    planState: 'tentative',
    title: 'Tempo run',
    intensityLabel: 'Moderate',
    estDurationMin: 55,
    coachNotes: 'Slightly longer threshold block than last week.',
    running: {
      runType: 'tempo',
      totalDistanceKm: 9,
      totalDurationMin: 55,
      targetPace: '5:15/km',
      targetHrZone: 3,
      targetRpe: 6,
      segments: [],
    },
  }),
  run({
    id: 'ps_8',
    weekIndex: 2,
    scheduledDate: '2026-07-05',
    planState: 'tentative',
    title: 'Long run',
    intensityLabel: 'Easy',
    estDurationMin: 90,
    startTime: '08:30',
    endTime: '10:00',
    scheduledStartUtc: '2026-07-05T06:30:00.000Z',
    coachNotes: 'Step up to 16K. Fuel beforehand.',
    running: {
      runType: 'long',
      totalDistanceKm: 16,
      totalDurationMin: 90,
      targetPace: '6:15/km',
      targetHrZone: 2,
      targetRpe: 4,
      segments: [],
    },
  }),
];
